/**
 * リリース向けデータ作成・第2弾（主要都市バッチ）
 *
 * 対象: 京都府(伏見・宇治／天橋立・丹後), 北海道(札幌市内／小樽・積丹／富良野・美瑛／函館),
 *       大阪府(梅田・大阪駅周辺／難波・道頓堀／天王寺・あべの／堺・泉南),
 *       奈良県(奈良市内／吉野／飛鳥),
 *       東京都(浅草・上野／渋谷・原宿／お台場・臨海副都心／吉祥寺・三鷹),
 *       福岡県(福岡市内／太宰府／門司港) の計20エリア。
 * 各エリアに日帰り〜4泊5日の5パターン、1日5スポット以上、移動手段・写真・訪問時刻など
 * 全項目を埋めて作成する。ロジックは prisma/lib/pilot-gen.ts を共有。
 *
 * 実行方法: npx tsx prisma/seed-batch2.ts
 *
 * ⚠️ 住所・緯度経度・公式サイトはAI(Claude)の知識をもとにした概算値。本番投入前に
 * 地図サービス等との突合による裏取りを推奨する。
 */
import { AreaSeed, generateAreas } from "./lib/pilot-gen";
import existingPhotoCache from "./photo-cache.json";

const AREAS: AreaSeed[] = [
  // ---- 京都府 ----
  {
    key: "fushimi_uji",
    areaId: "24c3f286-3ab9-4554-996e-afaefb778017",
    prefectureId: "30a8b9ca-07aa-4565-aa0e-64d7e07ca372",
    areaName: "伏見・宇治",
    prefectureName: "京都府",
    tagNames: ["定番観光", "紅葉"],
    purposeNames: ["お寺", "神社", "酒蔵・ワイナリー巡り"],
    titles: {
      0: "千本鳥居と抹茶の香り、伏見・宇治を歩く欲張り散策プラン",
      1: "伏見稲荷から平等院へ。朱と新緑に包まれる伏見・宇治めぐり",
      2: "酒蔵と源氏物語の里を巡る、伏見・宇治ゆったり旅",
      3: "千本鳥居・宇治川・お茶文化。伏見・宇治を味わい尽くす旅",
      4: "京都の隠れた名所まで。伏見・宇治じっくり探訪の旅",
    },
    spots: [
      { name: "伏見稲荷大社", address: "京都市伏見区深草藪之内町68", lat: 34.9671, lng: 135.7727, memo: "千本鳥居で世界的に有名な神社。稲荷山を登る参拝コースも人気。", websiteUrl: "https://inari.jp/", wikiTitle: "伏見稲荷大社" },
      { name: "宇治平等院", address: "宇治市宇治蓮華116", lat: 34.8892, lng: 135.808, memo: "10円硬貨にも描かれる鳳凰堂で知られる世界遺産。", websiteUrl: "https://www.byodoin.or.jp/", wikiTitle: "平等院" },
      { name: "月桂冠大倉記念館", address: "京都市伏見区南浜町247", lat: 34.9339, lng: 135.7621, memo: "伏見の酒蔵街にある資料館。日本酒の試飲も楽しめる。", websiteUrl: "https://www.gekkeikan.co.jp/", wikiTitle: "月桂冠大倉記念館" },
      { name: "宇治上神社", address: "宇治市宇治山田59", lat: 34.8912, lng: 135.8098, memo: "現存最古の神社建築とされる本殿を持つ世界遺産。", websiteUrl: "https://ja.kyoto.travel/", wikiTitle: "宇治上神社" },
      { name: "寺田屋", address: "京都市伏見区南浜町263", lat: 34.9328, lng: 135.7621, memo: "坂本龍馬ゆかりの旅籠。幕末の歴史を今に伝える。", websiteUrl: "https://ja.kyoto.travel/", wikiTitle: "寺田屋" },
      { name: "三室戸寺", address: "宇治市莵道滋賀谷21", lat: 34.8965, lng: 135.8214, memo: "1万株のアジサイと蓮で有名な「花の寺」。", websiteUrl: "https://www.mimurotoji.com/", wikiTitle: "三室戸寺" },
      { name: "十石舟（伏見）", address: "京都市伏見区南浜町周辺", lat: 34.9335, lng: 135.7627, memo: "酒蔵の白壁を水面から眺める、伏見名物の遊覧船。", websiteUrl: "https://ja.kyoto.travel/", wikiTitle: "伏見_(京都市)" },
      { name: "御香宮神社", address: "京都市伏見区御香宮門前町174", lat: 34.9358, lng: 135.7639, memo: "名水が湧くことからその名がついた伏見の氏神様。", websiteUrl: "https://ja.kyoto.travel/", wikiTitle: "御香宮神社" },
      { name: "宇治川", address: "宇治市", lat: 34.8907, lng: 135.8062, memo: "宇治橋から眺める清流。夏には鵜飼も行われる。", websiteUrl: "https://ja.kyoto.travel/", wikiTitle: "宇治川" },
      { name: "宇治市源氏物語ミュージアム", address: "宇治市宇治東内45-26", lat: 34.8916, lng: 135.8069, memo: "源氏物語「宇治十帖」の世界を体感できる博物館。", websiteUrl: "https://www.uji-genji.jp/", wikiTitle: "宇治市源氏物語ミュージアム" },
      { name: "萬福寺", address: "宇治市五ケ庄三番割34", lat: 34.911, lng: 135.8009, memo: "中国風の伽藍が特徴的な黄檗宗の大本山。", websiteUrl: "https://www.obakusan.or.jp/", wikiTitle: "萬福寺" },
      { name: "中村藤吉本店", address: "宇治市宇治壱番10", lat: 34.8905, lng: 135.8088, memo: "明治創業の老舗茶舗。宇治抹茶スイーツが人気。", websiteUrl: "https://www.tokichi.jp/", wikiTitle: "中村藤吉" },
      { name: "城南宮", address: "京都市伏見区中島鳥羽離宮町7", lat: 34.944, lng: 135.7614, memo: "方除けの神様として知られ、神苑「楽水苑」も美しい。", websiteUrl: "https://www.jonangu.com/", wikiTitle: "城南宮" },
      { name: "藤森神社", address: "京都市伏見区深草鳥居崎町609", lat: 34.9622, lng: 135.7695, memo: "勝運と馬の神社として競馬ファンの参拝も多い。", websiteUrl: "https://ja.kyoto.travel/", wikiTitle: "藤森神社" },
      { name: "石峰寺", address: "京都市伏見区深草石峰寺山町26", lat: 34.9636, lng: 135.7724, memo: "伊藤若冲が下絵を描いたとされる五百羅漢像で有名。", websiteUrl: "https://ja.kyoto.travel/", wikiTitle: "石峰寺" },
    ],
  },
  {
    key: "amanohashidate_tango",
    areaId: "9d4d8371-7b22-4216-9634-33b6f191d238",
    prefectureId: "30a8b9ca-07aa-4565-aa0e-64d7e07ca372",
    areaName: "天橋立・丹後",
    prefectureName: "京都府",
    tagNames: ["絶景", "海・リゾート"],
    purposeNames: ["絶景・フォトスポット", "神社", "ビーチ・海水浴"],
    titles: {
      0: "日本三景・天橋立を股のぞきで楽しむ丹後さんぽプラン",
      1: "天橋立と伊根の舟屋、海と絶景の丹後めぐり旅",
      2: "股のぞき絶景から舟屋の里まで、丹後半島満喫の旅",
      3: "丹後半島をぐるり一周。海の幸と絶景を味わう旅",
      4: "天橋立から経ヶ岬まで、丹後半島をとことん巡る旅",
    },
    spots: [
      { name: "天橋立", address: "宮津市文珠", lat: 35.5561, lng: 135.1892, memo: "日本三景の一つ。白砂青松が約3.6kmにわたって続く。", websiteUrl: "https://www.amanohashidate.jp/", wikiTitle: "天橋立" },
      { name: "天橋立ビューランド", address: "宮津市文珠437", lat: 35.554, lng: 135.1935, memo: "股のぞきで「天に架かる橋」を体感できる展望台。", websiteUrl: "https://www.viewland.jp/", wikiTitle: "天橋立ビューランド" },
      { name: "智恩寺（文殊堂）", address: "宮津市文珠466", lat: 35.5518, lng: 135.1917, memo: "日本三文殊の一つに数えられる、知恵の仏様を祀る寺。", websiteUrl: "https://ja.kyoto.travel/", wikiTitle: "智恩寺_(宮津市)" },
      { name: "傘松公園", address: "宮津市大垣130", lat: 35.5638, lng: 135.1888, memo: "北側から天橋立を望む、もう一つの股のぞき名所。", websiteUrl: "https://ja.kyoto.travel/", wikiTitle: "傘松公園" },
      { name: "籠神社", address: "宮津市大垣430", lat: 35.5622, lng: 135.1899, memo: "元伊勢とも呼ばれる、丹後国一宮の格式高い神社。", websiteUrl: "https://www.motoise.jp/", wikiTitle: "籠神社" },
      { name: "伊根の舟屋", address: "与謝郡伊根町平田", lat: 35.6935, lng: 135.2683, memo: "1階が船のガレージという独特の舟屋が並ぶ漁村風景。", websiteUrl: "https://ine-kankou.jp/", wikiTitle: "伊根町" },
      { name: "経ヶ岬灯台", address: "京丹後市丹後町袖志", lat: 35.7683, lng: 135.1256, memo: "丹後半島最北端、日本海を見渡す白亜の灯台。", websiteUrl: "https://ja.kyoto.travel/", wikiTitle: "経ヶ岬灯台" },
      { name: "琴引浜", address: "京丹後市網野町掛津", lat: 35.6919, lng: 134.9975, memo: "歩くと鳴き砂の音がする、全国有数の美しい海岸。", websiteUrl: "https://ja.kyoto.travel/", wikiTitle: "琴引浜" },
      { name: "丹後国分寺跡", address: "宮津市国分", lat: 35.5723, lng: 135.2214, memo: "天橋立を見下ろす高台に残る、奈良時代の寺院跡。", websiteUrl: "https://ja.kyoto.travel/", wikiTitle: "丹後国分寺跡" },
      { name: "加悦SL広場", address: "与謝郡与謝野町字加悦1830", lat: 35.4931, lng: 135.1367, memo: "貴重な蒸気機関車が並ぶ、鉄道ファンに人気のスポット。", websiteUrl: "https://ja.kyoto.travel/", wikiTitle: "加悦SL広場" },
      { name: "舟屋の里公園", address: "与謝郡伊根町平田507", lat: 35.689, lng: 135.268, memo: "伊根の舟屋群を一望できる展望スポット。", websiteUrl: "https://ine-kankou.jp/", wikiTitle: "伊根町" },
      { name: "丹後由良", address: "宮津市由良", lat: 35.5978, lng: 135.2508, memo: "小説「山椒大夫」の舞台としても知られる海水浴場。", websiteUrl: "https://ja.kyoto.travel/", wikiTitle: "丹後由良駅" },
      { name: "成相寺", address: "宮津市成相寺339", lat: 35.5677, lng: 135.1866, memo: "西国三十三所の霊場で、天橋立を一望できる山寺。", websiteUrl: "https://www.nariaiji.jp/", wikiTitle: "成相寺" },
    ],
  },
  // ---- 北海道 ----
  {
    key: "sapporo",
    areaId: "7409eef8-7b86-4be1-ac03-e9d4e3b614b4",
    prefectureId: "5cbf01f2-3e24-4913-8030-3285cb5734af",
    areaName: "札幌市内",
    prefectureName: "北海道",
    tagNames: ["定番観光", "グルメ"],
    purposeNames: ["神社", "美術館・博物館", "ショッピング"],
    titles: {
      0: "時計台から大通公園へ。札幌の街を気軽に楽しむプラン",
      1: "グルメも夜景も。札幌の魅力をぎゅっと詰め込んだ旅",
      2: "北海道神宮とモエレ沼公園、自然と街を楽しむ札幌旅",
      3: "定番から穴場まで。札幌の街をじっくり満喫する旅",
      4: "札幌の四季と食を味わい尽くす、じっくり滞在の旅",
    },
    spots: [
      { name: "札幌市時計台", address: "札幌市中央区北1条西2丁目", lat: 43.0621, lng: 141.3544, memo: "札幌のシンボルとして親しまれる、明治初期の洋風建築。", websiteUrl: "https://sapporoshi-tokeidai.jp/", wikiTitle: "札幌市時計台" },
      { name: "大通公園", address: "札幌市中央区大通西1〜12丁目", lat: 43.0596, lng: 141.3547, memo: "札幌の中心を東西に貫く公園。雪まつりの会場としても有名。", websiteUrl: "https://ja.kyoto.travel/", wikiTitle: "大通公園" },
      { name: "さっぽろテレビ塔", address: "札幌市中央区大通西1丁目", lat: 43.0605, lng: 141.3565, memo: "大通公園のシンボルタワー。展望台から街を一望できる。", websiteUrl: "https://www.tv-tower.co.jp/", wikiTitle: "さっぽろテレビ塔" },
      { name: "北海道庁旧本庁舎", address: "札幌市中央区北3条西6丁目", lat: 43.0637, lng: 141.3474, memo: "「赤れんが庁舎」の愛称で親しまれる明治期の洋風建築。", websiteUrl: "https://www.pref.hokkaido.lg.jp/", wikiTitle: "北海道庁旧本庁舎" },
      { name: "狸小路商店街", address: "札幌市中央区南2〜3条西1〜7丁目", lat: 43.0559, lng: 141.354, memo: "150年以上の歴史を持つ、北海道最大級のアーケード商店街。", websiteUrl: "https://www.tanukikoji.or.jp/", wikiTitle: "狸小路商店街" },
      { name: "二条市場", address: "札幌市中央区南3条東1丁目", lat: 43.0578, lng: 141.3573, memo: "新鮮な海鮮が並ぶ、札幌の台所と呼ばれる市場。", websiteUrl: "https://nijomarket.com/", wikiTitle: "二条市場" },
      { name: "北海道神宮", address: "札幌市中央区宮ケ丘474", lat: 43.0523, lng: 141.3084, memo: "北海道の総鎮守。円山の緑に囲まれた静かな杜。", websiteUrl: "https://www.hokkaidojingu.or.jp/", wikiTitle: "北海道神宮" },
      { name: "羊ヶ丘展望台", address: "札幌市豊平区羊ケ丘1", lat: 43.0, lng: 141.4103, memo: "クラーク博士像と札幌ドームを望む、市内を一望できる丘。", websiteUrl: "https://www.hitsujigaoka.jp/", wikiTitle: "羊ヶ丘展望台" },
      { name: "モエレ沼公園", address: "札幌市東区モエレ沼公園1-1", lat: 43.1136, lng: 141.4104, memo: "彫刻家イサム・ノグチが設計した、公園全体がアート作品。", websiteUrl: "https://moerenumapark.jp/", wikiTitle: "モエレ沼公園" },
      { name: "円山公園（札幌）", address: "札幌市中央区宮ケ丘", lat: 43.0546, lng: 141.3149, memo: "桜の名所として知られる、北海道神宮に隣接する公園。", websiteUrl: "https://ja.kyoto.travel/", wikiTitle: "円山公園_(札幌市)" },
      { name: "サッポロビール博物館", address: "札幌市東区北7条東9丁目2-10", lat: 43.0721, lng: 141.3706, memo: "日本で唯一のビール専門博物館。試飲も楽しめる。", websiteUrl: "https://www.sapporobeer.jp/brewery/s_museum/", wikiTitle: "サッポロビール博物館" },
      { name: "札幌市中央卸売市場場外市場", address: "札幌市中央区北11条西21丁目", lat: 43.0771, lng: 141.3283, memo: "海鮮丼や新鮮な魚介が味わえる、活気あふれる市場。", websiteUrl: "https://www.jyogaiichiba.com/", wikiTitle: "札幌市中央卸売市場" },
      { name: "白い恋人パーク", address: "札幌市西区宮の沢2条2丁目11-36", lat: 43.0698, lng: 141.2952, memo: "お菓子のテーマパーク。製造工程の見学や体験ができる。", websiteUrl: "https://www.shiroikoibitopark.jp/", wikiTitle: "白い恋人パーク" },
      { name: "すすきの", address: "札幌市中央区南4〜7条西3〜5丁目", lat: 43.0546, lng: 141.3538, memo: "北日本最大級の歓楽街。夜のグルメスポットとしても人気。", websiteUrl: "https://ja.kyoto.travel/", wikiTitle: "すすきの" },
      { name: "北海道大学", address: "札幌市北区北8条西5丁目", lat: 43.0764, lng: 141.3414, memo: "ポプラ並木やイチョウ並木が美しい、広大なキャンパス。", websiteUrl: "https://www.hokudai.ac.jp/", wikiTitle: "北海道大学" },
    ],
  },
  {
    key: "otaru_shakotan",
    areaId: "9eb63300-b659-4a57-af66-ff2ea2ee5503",
    prefectureId: "5cbf01f2-3e24-4913-8030-3285cb5734af",
    areaName: "小樽・積丹",
    prefectureName: "北海道",
    tagNames: ["絶景", "海・リゾート"],
    purposeNames: ["絶景・フォトスポット", "ショッピング", "ダイビング・シュノーケリング"],
    titles: {
      0: "小樽運河と青の洞窟、絶景をめぐる日帰り弾丸プラン",
      1: "運河の街・小樽と積丹ブルーを満喫する海辺の旅",
      2: "ガラス工芸と神威岬。小樽・積丹をゆったり味わう旅",
      3: "小樽の街並みから積丹の絶景岬まで、じっくり巡る旅",
      4: "運河・海鮮・絶景。小樽・積丹をとことん楽しむ旅",
    },
    spots: [
      { name: "小樽運河", address: "小樽市港町", lat: 43.1975, lng: 141.0027, memo: "石造倉庫とガス灯が並ぶ、小樽を代表する景観。", websiteUrl: "https://otaru.gr.jp/", wikiTitle: "小樽運河" },
      { name: "小樽運河プラザ", address: "小樽市色内2丁目1-20", lat: 43.1988, lng: 141.0018, memo: "小樽観光の拠点となる、明治期の倉庫を利用した施設。", websiteUrl: "https://otaru.gr.jp/", wikiTitle: "小樽運河" },
      { name: "堺町通り商店街", address: "小樽市堺町", lat: 43.1912, lng: 140.9994, memo: "ガラス工芸やオルゴールの店が並ぶ、レトロな通り。", websiteUrl: "https://otaru.gr.jp/", wikiTitle: "堺町通り" },
      { name: "小樽オルゴール堂本館", address: "小樽市住吉町4-1", lat: 43.1918, lng: 141.0, memo: "重厚な石造建築の中に、数万点のオルゴールが並ぶ。", websiteUrl: "https://otaru-orgel.co.jp/", wikiTitle: "小樽オルゴール堂" },
      { name: "北一硝子三号館", address: "小樽市堺町7-26", lat: 43.193, lng: 141.0002, memo: "石油ランプの灯る館内で、小樽ガラスの美しさを堪能できる。", websiteUrl: "https://www.kitaichiglass.co.jp/", wikiTitle: "北一硝子" },
      { name: "小樽市総合博物館", address: "小樽市手宮1丁目3-6", lat: 43.2076, lng: 141.0033, memo: "鉄道と科学の歴史を紹介する、北海道鉄道発祥の地。", websiteUrl: "https://otarumuse.jp/", wikiTitle: "小樽市総合博物館" },
      { name: "旧手宮線", address: "小樽市色内1丁目〜手宮1丁目", lat: 43.2, lng: 141.0, memo: "北海道最初の鉄道跡。線路沿いの散策路として整備されている。", websiteUrl: "https://otaru.gr.jp/", wikiTitle: "旧手宮線" },
      { name: "積丹岬", address: "積丹郡積丹町大字入舸町", lat: 43.3877, lng: 140.4383, memo: "「積丹ブルー」と呼ばれる透き通った海を望む岬。", websiteUrl: "https://shakotan-guide.com/", wikiTitle: "積丹岬" },
      { name: "神威岬", address: "積丹郡積丹町大字神岬町", lat: 43.3593, lng: 140.3628, memo: "断崖に続く遊歩道の先にある、積丹を代表する絶景スポット。", websiteUrl: "https://shakotan-guide.com/", wikiTitle: "神威岬" },
      { name: "積丹半島（美国町）", address: "積丹郡積丹町美国町", lat: 43.3444, lng: 140.6083, memo: "青の洞窟クルーズの発着地。透明度の高い海が広がる。", websiteUrl: "https://shakotan-guide.com/", wikiTitle: "積丹半島" },
      { name: "鰊御殿（旧青山別邸）", address: "小樽市祝津3丁目63", lat: 43.2276, lng: 141.0033, memo: "ニシン漁で栄えた網元の豪邸。当時の繁栄を今に伝える。", websiteUrl: "https://otaru.gr.jp/", wikiTitle: "鰊御殿" },
      { name: "おたる水族館", address: "小樽市祝津3丁目303", lat: 43.2295, lng: 141.0025, memo: "北海道の海の生き物を中心に展示する、海辺の水族館。", websiteUrl: "https://otaru-aq.jp/", wikiTitle: "小樽水族館" },
      { name: "天狗山", address: "小樽市最上2丁目16-15", lat: 43.1806, lng: 140.9928, memo: "ロープウェイで登れる、小樽市街と石狩湾を一望できる山。", websiteUrl: "https://tenguyama.ckk.chuo-bus.co.jp/", wikiTitle: "天狗山_(小樽市)" },
    ],
  },
  {
    key: "furano_biei",
    areaId: "42f71eda-7fa8-40cd-9281-d6782c45673a",
    prefectureId: "5cbf01f2-3e24-4913-8030-3285cb5734af",
    areaName: "富良野・美瑛",
    prefectureName: "北海道",
    tagNames: ["絶景", "家族旅行"],
    purposeNames: ["絶景・フォトスポット", "自然", "高原・避暑"],
    titles: {
      0: "青い池とラベンダー畑、パッチワークの丘を巡る日帰りプラン",
      1: "花と丘の絶景を巡る、富良野・美瑛のフォトジェニック旅",
      2: "ラベンダー畑から青い池まで、北海道の丘をゆったり巡る旅",
      3: "四季彩の丘・青い池・望岳台。富良野・美瑛満喫の旅",
      4: "北海道の丘をとことん味わう、富良野・美瑛じっくり旅",
    },
    spots: [
      { name: "ファーム富田", address: "空知郡中富良野町基線北15号", lat: 43.46, lng: 142.4667, memo: "一面に広がるラベンダー畑で有名な、富良野を代表する花畑。", websiteUrl: "https://www.farm-tomita.co.jp/", wikiTitle: "ファーム富田" },
      { name: "青い池", address: "上川郡美瑛町白金", lat: 43.611, lng: 142.6817, memo: "水面が青く輝く、美瑛を代表する神秘的なスポット。", websiteUrl: "https://biei-hokkaido.jp/", wikiTitle: "青い池" },
      { name: "四季彩の丘", address: "上川郡美瑛町新星第三", lat: 43.5464, lng: 142.4869, memo: "虹色の花畑が丘一面に広がる、美瑛の人気観光農園。", websiteUrl: "https://shikisainooka.jp/", wikiTitle: "四季彩の丘" },
      { name: "白ひげの滝", address: "上川郡美瑛町白金", lat: 43.6122, lng: 142.6839, memo: "青い水面に流れ落ちる、美瑛川沿いの美しい滝。", websiteUrl: "https://biei-hokkaido.jp/", wikiTitle: "白ひげの滝" },
      { name: "美瑛の丘（パッチワークの路）", address: "上川郡美瑛町", lat: 43.59, lng: 142.44, memo: "色とりどりの畑が織りなす、パッチワークのような丘陵地帯。", websiteUrl: "https://biei-hokkaido.jp/", wikiTitle: "美瑛町" },
      { name: "ケンとメリーの木", address: "上川郡美瑛町北瑛", lat: 43.5975, lng: 142.4256, memo: "CMで有名になった、丘の上にそびえる一本のポプラの木。", websiteUrl: "https://biei-hokkaido.jp/", wikiTitle: "ケンとメリーの木" },
      { name: "新富良野プリンスホテル・ニングルテラス", address: "富良野市中御料", lat: 43.3167, lng: 142.375, memo: "森の中に立つログハウス群のショップ街。夜の散策も人気。", websiteUrl: "https://www.princehotels.co.jp/shinfurano/", wikiTitle: "ニングルテラス" },
      { name: "麓郷の森", address: "富良野市東麓郷", lat: 43.2833, lng: 142.5, memo: "ドラマ「北の国から」のロケ地として知られる森。", websiteUrl: "https://www.furanotourism.com/", wikiTitle: "麓郷" },
      { name: "十勝岳望岳台", address: "上川郡美瑛町白金", lat: 43.6497, lng: 142.6875, memo: "活火山・十勝岳連峰を間近に望む、雄大な高原展望台。", websiteUrl: "https://biei-hokkaido.jp/", wikiTitle: "望岳台" },
      { name: "拓真館", address: "上川郡美瑛町美田", lat: 43.535, lng: 142.4544, memo: "美瑛の風景写真で有名な前田真三の作品を展示するギャラリー。", websiteUrl: "https://takushinkan.gallery/", wikiTitle: "拓真館" },
      { name: "三愛の丘展望公園", address: "上川郡美瑛町大久保協生", lat: 43.6069, lng: 142.4744, memo: "美瑛の丘陵風景を360度見渡せる小さな展望公園。", websiteUrl: "https://biei-hokkaido.jp/", wikiTitle: "美瑛町" },
    ],
  },
  {
    key: "hakodate",
    areaId: "342c7f96-5ded-4a8b-a843-041ff3f21f98",
    prefectureId: "5cbf01f2-3e24-4913-8030-3285cb5734af",
    areaName: "函館",
    prefectureName: "北海道",
    tagNames: ["絶景", "温泉"],
    purposeNames: ["夜景", "城・史跡", "温泉"],
    titles: {
      0: "函館山の夜景と異国情緒あふれる街並みを楽しむプラン",
      1: "五稜郭と元町、函館の歴史と夜景を巡る旅",
      2: "函館山・赤レンガ倉庫・湯の川温泉、函館満喫の旅",
      3: "異国情緒と絶景を味わい尽くす、函館じっくり旅",
      4: "大沼公園まで足をのばす、函館とことん探訪の旅",
    },
    spots: [
      { name: "函館山", address: "函館市函館山", lat: 41.7553, lng: 140.7078, memo: "「世界三大夜景」の一つに数えられる、函館随一の絶景スポット。", websiteUrl: "https://334.co.jp/", wikiTitle: "函館山" },
      { name: "五稜郭公園", address: "函館市五稜郭町44", lat: 41.7969, lng: 140.7566, memo: "星形の特徴的な城郭跡。桜の名所としても有名。", websiteUrl: "https://www.hakodate-goryokaku.jp/", wikiTitle: "五稜郭" },
      { name: "五稜郭タワー", address: "函館市五稜郭町43-9", lat: 41.7975, lng: 140.7561, memo: "五稜郭の星形を上から一望できる展望タワー。", websiteUrl: "https://www.goryokaku-tower.co.jp/", wikiTitle: "五稜郭タワー" },
      { name: "金森赤レンガ倉庫", address: "函館市末広町14-12", lat: 41.7767, lng: 140.7186, memo: "明治期の倉庫群を活用した、ショップやレストランが並ぶ人気スポット。", websiteUrl: "https://hakodate-kanemori.com/", wikiTitle: "金森赤レンガ倉庫" },
      { name: "函館朝市", address: "函館市若松町9-19", lat: 41.7736, lng: 140.7228, memo: "新鮮な海鮮丼やイカ釣り体験が楽しめる、函館名物の朝市。", websiteUrl: "https://hakodate-asaichi.com/", wikiTitle: "函館朝市" },
      { name: "函館ハリストス正教会", address: "函館市元町3-13", lat: 41.7714, lng: 140.7169, memo: "「ガンガン寺」の愛称で親しまれる、異国情緒あふれる教会。", websiteUrl: "https://hakodate-orthodox-church.com/", wikiTitle: "函館ハリストス正教会" },
      { name: "旧函館区公会堂", address: "函館市元町11-13", lat: 41.7726, lng: 140.7187, memo: "コロニアル様式の華やかな洋館。元町の高台に建つ。", websiteUrl: "https://www.zaidan-hakodate.com/kokaido/", wikiTitle: "旧函館区公会堂" },
      { name: "トラピスチヌ修道院", address: "函館市上湯川町346", lat: 41.7767, lng: 140.7933, memo: "日本初の女子観想修道院。美しいマリア像と庭園が見どころ。", websiteUrl: "https://ja.kyoto.travel/", wikiTitle: "トラピスチヌ修道院" },
      { name: "湯の川温泉", address: "函館市湯川町", lat: 41.7825, lng: 140.7906, memo: "函館空港にも近い、道南を代表する温泉街。", websiteUrl: "https://hakodate-yunokawa.jp/", wikiTitle: "湯の川温泉" },
      { name: "立待岬", address: "函館市住吉町", lat: 41.7419, lng: 140.7297, memo: "津軽海峡を望む、石川啄木ゆかりの景勝地。", websiteUrl: "https://ja.kyoto.travel/", wikiTitle: "立待岬" },
      { name: "大沼国定公園", address: "亀田郡七飯町大沼町1023", lat: 41.9772, lng: 140.6822, memo: "駒ヶ岳を望む湖沼群。サイクリングや遊覧船が楽しめる。", websiteUrl: "https://onuma-guide.com/", wikiTitle: "大沼国定公園" },
      { name: "函館ベイエリア（はこだて明治館）", address: "函館市豊川町11-17", lat: 41.7746, lng: 140.7208, memo: "赤レンガの旧郵便局を利用したショッピングスポット。", websiteUrl: "https://www.meijikan.com/", wikiTitle: "函館市" },
    ],
  },
  // ---- 大阪府 ----
  {
    key: "umeda",
    areaId: "960beb9a-6dc0-400d-8618-e0815aca4d23",
    prefectureId: "60fa046c-6b5c-4596-93c8-af5c7e8a0a5f",
    areaName: "梅田・大阪駅周辺",
    prefectureName: "大阪府",
    tagNames: ["定番観光", "グルメ"],
    purposeNames: ["ショッピング", "神社", "美術館・博物館"],
    titles: {
      0: "空中庭園から天満宮へ。梅田の高層ビル街を楽しむプラン",
      1: "グランフロントと中崎町、新旧が交わる梅田さんぽ旅",
      2: "空中庭園・中之島・天神橋筋、大阪駅周辺をゆったり巡る旅",
      3: "ビル街から下町まで。梅田・大阪駅周辺を満喫する旅",
      4: "大阪の玄関口をとことん楽しむ、梅田じっくり滞在の旅",
    },
    spots: [
      { name: "梅田スカイビル", address: "大阪市北区大淀中1-1-88", lat: 34.7053, lng: 135.4906, memo: "空中庭園展望台からの360度パノラマが人気のランドマーク。", websiteUrl: "https://www.kuchu-teien.com/", wikiTitle: "梅田スカイビル" },
      { name: "グランフロント大阪", address: "大阪市北区大深町4-1", lat: 34.7025, lng: 135.4959, memo: "大阪駅直結の複合商業施設。ショップやレストランが充実。", websiteUrl: "https://www.grandfront-osaka.jp/", wikiTitle: "グランフロント大阪" },
      { name: "HEP FIVE観覧車", address: "大阪市北区角田町5-15", lat: 34.7028, lng: 135.5011, memo: "ビルの屋上に設置された、赤い観覧車が目印の商業施設。", websiteUrl: "https://www.hepfive.jp/", wikiTitle: "HEP_FIVE" },
      { name: "中崎町", address: "大阪市北区中崎西1〜3丁目", lat: 34.7059, lng: 135.5058, memo: "昔ながらの長屋を改装したカフェが並ぶ、レトロな街並み。", websiteUrl: "https://ja.kyoto.travel/", wikiTitle: "中崎町" },
      { name: "大阪天満宮", address: "大阪市北区天神橋2丁目1-8", lat: 34.697, lng: 135.5136, memo: "学問の神様を祀る、天神祭でも知られる大阪の名社。", websiteUrl: "https://osakatemmangu.or.jp/", wikiTitle: "大阪天満宮" },
      { name: "天神橋筋商店街", address: "大阪市北区・都島区", lat: 34.698, lng: 135.515, memo: "日本一長いとされるアーケード商店街。庶民の活気にあふれる。", websiteUrl: "https://tenjinbashi.or.jp/", wikiTitle: "天神橋筋商店街" },
      { name: "中之島公園", address: "大阪市北区中之島1丁目", lat: 34.6928, lng: 135.5, memo: "堂島川と土佐堀川に挟まれた、バラ園が美しい中之島の公園。", websiteUrl: "https://www.osakapark.osgf.or.jp/nakanoshima/", wikiTitle: "中之島公園" },
      { name: "大阪市中央公会堂", address: "大阪市北区中之島1-1-27", lat: 34.6935, lng: 135.5011, memo: "ネオ・ルネサンス様式の重厚な外観を持つ、大阪の迎賓館。", websiteUrl: "https://osaka-chuokokaido.jp/", wikiTitle: "大阪市中央公会堂" },
      { name: "扇町公園", address: "大阪市北区扇町2", lat: 34.7017, lng: 135.5108, memo: "梅田の喧騒から少し離れた、市民に親しまれる緑豊かな公園。", websiteUrl: "https://ja.kyoto.travel/", wikiTitle: "扇町公園" },
      { name: "大阪市立東洋陶磁美術館", address: "大阪市北区中之島1-1-26", lat: 34.6939, lng: 135.5013, memo: "世界屈指の東洋陶磁コレクションを誇る美術館。", websiteUrl: "https://www.moco.or.jp/", wikiTitle: "大阪市立東洋陶磁美術館" },
      { name: "グラングリーン大阪（うめきた公園）", address: "大阪市北区大深町", lat: 34.704, lng: 135.495, memo: "大阪駅前に誕生した、都会のオアシスとなる大規模都市公園。", websiteUrl: "https://www.grandgreen-osaka.jp/", wikiTitle: "グラングリーン大阪" },
      { name: "露天神社（お初天神）", address: "大阪市北区曽根崎2丁目5-4", lat: 34.7012, lng: 135.4998, memo: "「曽根崎心中」の舞台として知られる、縁結びの神社。", websiteUrl: "https://www.ohatujitenjin.com/", wikiTitle: "露天神社" },
      { name: "茶屋町", address: "大阪市北区茶屋町", lat: 34.7052, lng: 135.5019, memo: "個性的なショップやカフェが集まる、梅田の若者文化発信地。", websiteUrl: "https://ja.kyoto.travel/", wikiTitle: "茶屋町_(大阪市)" },
    ],
  },
  {
    key: "namba_dotonbori",
    areaId: "9878a6ef-cbaa-4028-a933-04f0863d6ce1",
    prefectureId: "60fa046c-6b5c-4596-93c8-af5c7e8a0a5f",
    areaName: "難波・道頓堀",
    prefectureName: "大阪府",
    tagNames: ["グルメ", "定番観光"],
    purposeNames: ["ショッピング", "夜景", "神社"],
    titles: {
      0: "グリコサインとたこ焼き、道頓堀を食べ歩く日帰りプラン",
      1: "道頓堀の夜景と新世界のレトロ感、なにわ食い倒れ旅",
      2: "黒門市場からアメ村まで、ミナミの街を満喫する旅",
      3: "食い倒れも下町散策も。難波・道頓堀を味わい尽くす旅",
      4: "通天閣から法善寺横丁まで、なにわの街をとことん巡る旅",
    },
    spots: [
      { name: "道頓堀", address: "大阪市中央区道頓堀1丁目", lat: 34.6687, lng: 135.5013, memo: "グリコの看板で有名な、大阪ミナミを代表する繁華街。", websiteUrl: "https://www.dotonbori.or.jp/", wikiTitle: "道頓堀" },
      { name: "心斎橋筋商店街", address: "大阪市中央区心斎橋筋1〜2丁目", lat: 34.6725, lng: 135.5013, memo: "南北600mに続く、大阪屈指のショッピングアーケード。", websiteUrl: "https://www.shinsaibashi.or.jp/", wikiTitle: "心斎橋筋商店街" },
      { name: "法善寺横丁", address: "大阪市中央区難波1丁目", lat: 34.6679, lng: 135.5025, memo: "石畳が続く、大阪の風情を今に伝える飲食店街。", websiteUrl: "https://ja.kyoto.travel/", wikiTitle: "法善寺横丁" },
      { name: "なんばグランド花月", address: "大阪市中央区難波千日前11-6", lat: 34.6656, lng: 135.5033, memo: "吉本新喜劇や漫才を楽しめる、お笑いの殿堂。", websiteUrl: "https://www.yoshimoto.co.jp/ngk/", wikiTitle: "なんばグランド花月" },
      { name: "黒門市場", address: "大阪市中央区日本橋2丁目", lat: 34.6656, lng: 135.5064, memo: "「大阪の台所」と呼ばれる、新鮮な食材が並ぶ市場。", websiteUrl: "https://www.kuromon.com/", wikiTitle: "黒門市場" },
      { name: "通天閣", address: "大阪市浪速区恵美須東1丁目18-6", lat: 34.6524, lng: 135.5061, memo: "新世界のシンボルタワー。ビリケンさんでも有名。", websiteUrl: "https://www.tsutenkaku.co.jp/", wikiTitle: "通天閣" },
      { name: "新世界", address: "大阪市浪速区恵美須東", lat: 34.652, lng: 135.5064, memo: "串カツ店が軒を連ねる、レトロで活気あふれる下町エリア。", websiteUrl: "https://www.shinsekai-net.jp/", wikiTitle: "新世界_(大阪)" },
      { name: "でんでんタウン", address: "大阪市浪速区日本橋", lat: 34.6636, lng: 135.5061, memo: "電気街として発展した、大阪の秋葉原とも呼ばれる街。", websiteUrl: "https://www.denden-town.or.jp/", wikiTitle: "でんでんタウン" },
      { name: "千日前道具屋筋商店街", address: "大阪市中央区難波千日前", lat: 34.666, lng: 135.5044, memo: "プロ向けの調理器具や食品サンプルの店が並ぶ専門商店街。", websiteUrl: "https://www.doguyasuji.or.jp/", wikiTitle: "千日前道具屋筋商店街" },
      { name: "アメリカ村", address: "大阪市中央区西心斎橋1〜2丁目", lat: 34.6725, lng: 135.4989, memo: "若者文化の発信地。古着屋やカフェが集まるエリア。", websiteUrl: "https://americamura.jp/", wikiTitle: "アメリカ村" },
      { name: "大阪松竹座", address: "大阪市中央区道頓堀1丁目9-19", lat: 34.6684, lng: 135.5017, memo: "西洋建築とアール・デコが融合した、歴史ある劇場。", websiteUrl: "https://www.shochiku.co.jp/play/theater/104/", wikiTitle: "大阪松竹座" },
      { name: "難波八阪神社", address: "大阪市浪速区元町2丁目9-19", lat: 34.6614, lng: 135.4986, memo: "巨大な獅子殿が目を引く、商売繁盛の神社。", websiteUrl: "https://nambayasaka.jp/", wikiTitle: "難波八阪神社" },
    ],
  },
  {
    key: "tennoji_abeno",
    areaId: "cea54099-3466-468b-951e-23eb8b0ea09b",
    prefectureId: "60fa046c-6b5c-4596-93c8-af5c7e8a0a5f",
    areaName: "天王寺・あべの",
    prefectureName: "大阪府",
    tagNames: ["定番観光", "家族旅行"],
    purposeNames: ["お寺", "動物園・水族館", "美術館・博物館"],
    titles: {
      0: "あべのハルカスと四天王寺、天王寺の絶景と歴史を巡るプラン",
      1: "空の展望台と下町情緒。天王寺・あべのぶらり旅",
      2: "動物園から一心寺まで、天王寺エリアをゆったり満喫する旅",
      3: "大阪最古の寺と最新の高層ビル。天王寺じっくり旅",
      4: "天王寺・あべのの魅力をとことん味わう、じっくり探訪の旅",
    },
    spots: [
      { name: "あべのハルカス", address: "大阪市阿倍野区阿倍野筋1丁目1-43", lat: 34.6457, lng: 135.5133, memo: "日本有数の高さを誇る超高層ビル。展望台からの眺めは圧巻。", websiteUrl: "https://www.abenoharukas-300.jp/", wikiTitle: "あべのハルカス" },
      { name: "四天王寺", address: "大阪市天王寺区四天王寺1丁目11-18", lat: 34.6553, lng: 135.5164, memo: "聖徳太子建立とされる、日本仏法最初の官寺。", websiteUrl: "https://www.shitennoji.or.jp/", wikiTitle: "四天王寺" },
      { name: "天王寺公園（てんしば）", address: "大阪市天王寺区茶臼山町5-55", lat: 34.6497, lng: 135.515, memo: "芝生広場とカフェが並ぶ、リニューアルされた都市公園。", websiteUrl: "https://www.tennoji-park.jp/tenshiba/", wikiTitle: "天王寺公園" },
      { name: "大阪市立美術館", address: "大阪市天王寺区茶臼山町1-82", lat: 34.6511, lng: 135.515, memo: "天王寺公園内に建つ、日本・東洋美術のコレクションで知られる美術館。", websiteUrl: "https://www.osaka-art-museum.jp/", wikiTitle: "大阪市立美術館" },
      { name: "天王寺動物園", address: "大阪市天王寺区茶臼山町1-108", lat: 34.6494, lng: 135.5122, memo: "100年以上の歴史を持つ、日本有数の都市型動物園。", websiteUrl: "https://www.tennojizoo.jp/", wikiTitle: "天王寺動物園" },
      { name: "一心寺", address: "大阪市天王寺区逢阪2丁目8-69", lat: 34.6522, lng: 135.5153, memo: "納骨した遺骨で作る「お骨佛」で知られる、庶民信仰の寺。", websiteUrl: "https://www.isshinji.or.jp/", wikiTitle: "一心寺" },
      { name: "安居神社", address: "大阪市天王寺区逢阪1丁目3-24", lat: 34.6532, lng: 135.5142, memo: "真田幸村の最期の地と伝わる、静かな境内を持つ神社。", websiteUrl: "https://ja.kyoto.travel/", wikiTitle: "安居神社" },
      { name: "阪堺電車天王寺駅前停留場", address: "大阪市阿倍野区旭町1丁目", lat: 34.6465, lng: 135.5134, memo: "「チンチン電車」の愛称で親しまれる、下町を走る路面電車。", websiteUrl: "https://www.hankai.co.jp/", wikiTitle: "阪堺電気軌道" },
      { name: "桃ヶ池公園", address: "大阪市阿倍野区桃ケ池町1丁目", lat: 34.635, lng: 135.5153, memo: "大きな池を中心に整備された、地元に愛される公園。", websiteUrl: "https://ja.kyoto.travel/", wikiTitle: "桃ヶ池公園" },
      { name: "あべのキューズモール", address: "大阪市阿倍野区阿倍野筋1丁目6-1", lat: 34.6466, lng: 135.5147, memo: "天王寺・あべの地区最大級のショッピングモール。", websiteUrl: "https://abenoq.com/", wikiTitle: "あべのキューズモール" },
      { name: "堀越神社", address: "大阪市天王寺区茶臼山町5-8", lat: 34.6503, lng: 135.5157, memo: "「一生に一度の願い」を叶えるとされる、聖徳太子ゆかりの神社。", websiteUrl: "https://ja.kyoto.travel/", wikiTitle: "堀越神社" },
      { name: "大江神社", address: "大阪市天王寺区夕陽丘町5-59", lat: 34.658, lng: 135.5183, memo: "四天王寺の鎮守社の一つ。狛虎が祀られる珍しい神社。", websiteUrl: "https://ja.kyoto.travel/", wikiTitle: "大江神社" },
    ],
  },
  {
    key: "sakai_sennan",
    areaId: "a98a6bd3-2d4d-490a-936f-a09c9ca99021",
    prefectureId: "60fa046c-6b5c-4596-93c8-af5c7e8a0a5f",
    areaName: "堺・泉南",
    prefectureName: "大阪府",
    tagNames: ["定番観光", "海・リゾート"],
    purposeNames: ["城・史跡", "ビーチ・海水浴", "ショッピング"],
    titles: {
      0: "世界遺産・仁徳天皇陵から刃物の街を巡る堺日帰りプラン",
      1: "古墳と伝統産業、堺の歴史をたどる旅",
      2: "百舌鳥古墳群から関空の絶景まで、堺・泉南満喫の旅",
      3: "古代史とビーチ・アウトレットも。堺・泉南を味わい尽くす旅",
      4: "堺・泉南の歴史と海をとことん楽しむ、じっくり旅",
    },
    spots: [
      { name: "仁徳天皇陵古墳（大仙古墳）", address: "堺市堺区大仙町", lat: 34.5653, lng: 135.4831, memo: "世界最大級の墳墓とされる、百舌鳥古墳群の中心的存在。", websiteUrl: "https://www.mozu-furuichi.jp/", wikiTitle: "仁徳天皇陵古墳" },
      { name: "堺市博物館", address: "堺市堺区百舌鳥夕雲町2丁200-1", lat: 34.5636, lng: 135.4844, memo: "古墳や堺の歴史を分かりやすく紹介する博物館。", websiteUrl: "https://www.city.sakai.lg.jp/museum/", wikiTitle: "堺市博物館" },
      { name: "百舌鳥古墳群", address: "堺市堺区", lat: 34.5644, lng: 135.4844, memo: "仁徳天皇陵をはじめとする古墳群。世界文化遺産に登録。", websiteUrl: "https://www.mozu-furuichi.jp/", wikiTitle: "百舌鳥古墳群" },
      { name: "堺伝統産業会館", address: "堺市堺区宿院町西2丁1-1", lat: 34.5714, lng: 135.4794, memo: "堺打刃物や線香など、伝統工芸品を紹介・販売する施設。", websiteUrl: "https://www.sakaidensan.jp/", wikiTitle: "堺市" },
      { name: "南宗寺", address: "堺市堺区南旅篭町東3丁1-2", lat: 34.567, lng: 135.4783, memo: "千利休ゆかりの禅寺。枯山水の庭園でも知られる。", websiteUrl: "https://nanshuji.or.jp/", wikiTitle: "南宗寺" },
      { name: "さかい利晶の杜", address: "堺市堺区宿院町西2丁1-1", lat: 34.5715, lng: 135.4789, memo: "千利休と与謝野晶子、二人の堺の偉人を紹介する文化施設。", websiteUrl: "https://www.sakai-rishonomori.com/", wikiTitle: "さかい利晶の杜" },
      { name: "りんくうプレミアム・アウトレット", address: "泉佐野市りんくう往来南3-28", lat: 34.4083, lng: 135.305, memo: "関西国際空港近くにある、海沿いの大型アウトレットモール。", websiteUrl: "https://www.premiumoutlets.co.jp/rinku/", wikiTitle: "りんくうプレミアム・アウトレット" },
      { name: "りんくう公園", address: "泉佐野市りんくう往来北1", lat: 34.4053, lng: 135.3006, memo: "関西国際空港を望む、夕日の名所としても人気の公園。", websiteUrl: "https://www.rinku-park.com/", wikiTitle: "りんくう公園" },
      { name: "淡輪ときめきビーチ", address: "泉南郡岬町淡輪", lat: 34.3439, lng: 135.1808, memo: "大阪府内でも屈指の透明度を誇る、人気の海水浴場。", websiteUrl: "https://ja.kyoto.travel/", wikiTitle: "岬町" },
      { name: "犬鳴山", address: "泉佐野市大木", lat: 34.3789, lng: 135.3939, memo: "七宝滝寺を中心とする、修験道の山として知られる景勝地。", websiteUrl: "https://ja.kyoto.travel/", wikiTitle: "犬鳴山" },
      { name: "二色の浜公園", address: "貝塚市二色南町", lat: 34.4258, lng: 135.3492, memo: "白砂の海岸が続く、大阪府内屈指の海浜公園。", websiteUrl: "https://www.nishiki-park.jp/", wikiTitle: "二色の浜公園" },
      { name: "水間寺", address: "貝塚市水間638", lat: 34.4269, lng: 135.4114, memo: "厄除け観音として親しまれる、日本最古の厄除け寺の一つ。", websiteUrl: "https://mizumadera.or.jp/", wikiTitle: "水間寺" },
    ],
  },
  // ---- 奈良県 ----
  {
    key: "nara_city",
    areaId: "25e03ca8-4d89-48c4-b1a0-273b354c1299",
    prefectureId: "dcfe71f9-c52c-44fc-b29f-9e4ccaccca73",
    areaName: "奈良市内",
    prefectureName: "奈良県",
    tagNames: ["定番観光", "紅葉"],
    purposeNames: ["お寺", "神社", "美術館・博物館"],
    titles: {
      0: "東大寺と奈良公園の鹿に会える、大仏さまめぐりプラン",
      1: "大仏さまと鹿、ならまちの町家。奈良の魅力を巡る旅",
      2: "東大寺・春日大社・薬師寺、古都奈良をゆったり巡る旅",
      3: "世界遺産の寺社をめぐる、奈良じっくり探訪の旅",
      4: "古都奈良の歴史と自然をとことん味わう、じっくり旅",
    },
    spots: [
      { name: "東大寺", address: "奈良市雑司町406-1", lat: 34.6889, lng: 135.8398, memo: "奈良の大仏で知られる、世界最大級の木造建築を持つ寺院。", websiteUrl: "https://www.todaiji.or.jp/", wikiTitle: "東大寺" },
      { name: "奈良公園", address: "奈良市登大路町30", lat: 34.6851, lng: 135.843, memo: "1200頭以上の鹿が暮らす、奈良を代表する広大な公園。", websiteUrl: "https://www3.pref.nara.jp/park/", wikiTitle: "奈良公園" },
      { name: "春日大社", address: "奈良市春日野町160", lat: 34.6813, lng: 135.8481, memo: "朱塗りの社殿と数千基の灯籠が並ぶ、世界遺産の神社。", websiteUrl: "https://www.kasugataisha.or.jp/", wikiTitle: "春日大社" },
      { name: "興福寺", address: "奈良市登大路町48", lat: 34.6836, lng: 135.8353, memo: "五重塔が奈良のシンボルとなっている、藤原氏ゆかりの寺院。", websiteUrl: "https://www.kohfukuji.com/", wikiTitle: "興福寺" },
      { name: "奈良町（ならまち）", address: "奈良市中院町周辺", lat: 34.6785, lng: 135.83, memo: "格子造りの町家が残る、風情ある旧市街地。", websiteUrl: "https://naramachiinfo.jp/", wikiTitle: "奈良町" },
      { name: "猿沢池", address: "奈良市登大路町49", lat: 34.6803, lng: 135.833, memo: "興福寺の五重塔を水面に映す、奈良を代表する景勝地。", websiteUrl: "https://ja.kyoto.travel/", wikiTitle: "猿沢池" },
      { name: "元興寺", address: "奈良市中院町11", lat: 34.6791, lng: 135.832, memo: "飛鳥時代創建の古刹。世界最古級の瓦が今も屋根に残る。", websiteUrl: "https://gangoji-tera.or.jp/", wikiTitle: "元興寺" },
      { name: "平城宮跡歴史公園", address: "奈良市二条大路南3丁目5-1", lat: 34.6851, lng: 135.7956, memo: "奈良時代の都の中心地。朱雀門などが復原されている。", websiteUrl: "https://www.heijo-park.go.jp/", wikiTitle: "平城宮跡" },
      { name: "奈良国立博物館", address: "奈良市登大路町50", lat: 34.6828, lng: 135.8394, memo: "仏教美術を中心とした、日本有数のコレクションを誇る博物館。", websiteUrl: "https://www.narahaku.go.jp/", wikiTitle: "奈良国立博物館" },
      { name: "唐招提寺", address: "奈良市五条町13-46", lat: 34.6772, lng: 135.7889, memo: "唐僧・鑑真が創建した、優美な金堂で知られる世界遺産の寺。", websiteUrl: "https://toshodaiji.jp/", wikiTitle: "唐招提寺" },
      { name: "薬師寺", address: "奈良市西ノ京町457", lat: 34.6689, lng: 135.7867, memo: "白鳳伽藍の美しさで知られる、法相宗の大本山。", websiteUrl: "https://yakushiji.or.jp/", wikiTitle: "薬師寺" },
      { name: "依水園", address: "奈良市水門町74", lat: 34.687, lng: 135.8408, memo: "東大寺の借景を活かした、江戸期と明治期の二つの庭園。", websiteUrl: "https://isuien.or.jp/", wikiTitle: "依水園" },
      { name: "般若寺", address: "奈良市般若寺町221", lat: 34.701, lng: 135.8317, memo: "秋のコスモスで有名な、「コスモス寺」の愛称を持つ古刹。", websiteUrl: "https://hannyaji.com/", wikiTitle: "般若寺" },
    ],
  },
  {
    key: "yoshino",
    areaId: "429df8c5-77d4-4a2f-9a3a-3fc905f45455",
    prefectureId: "dcfe71f9-c52c-44fc-b29f-9e4ccaccca73",
    areaName: "吉野",
    prefectureName: "奈良県",
    tagNames: ["絶景", "紅葉"],
    purposeNames: ["花見・桜", "お寺", "ハイキング・登山"],
    titles: {
      0: "一目千本、桜の名所・吉野山を巡る日帰りプラン",
      1: "金峯山寺と吉水神社、桜と信仰の山・吉野を歩く旅",
      2: "下千本から奥千本まで、吉野山をゆったり巡る旅",
      3: "世界遺産の霊山・吉野を味わい尽くす、じっくり旅",
      4: "吉野山の四季と信仰の歴史をとことん辿る旅",
    },
    spots: [
      { name: "吉野山", address: "吉野郡吉野町吉野山", lat: 34.3608, lng: 135.8672, memo: "「一目千本」と称される、日本一の桜の名所。", websiteUrl: "https://www.yoshinoyama-sakura.jp/", wikiTitle: "吉野山" },
      { name: "金峯山寺", address: "吉野郡吉野町吉野山2500", lat: 34.3639, lng: 135.8672, memo: "修験道の総本山。巨大な蔵王堂は国宝に指定されている。", websiteUrl: "https://www.kinpusen.or.jp/", wikiTitle: "金峯山寺" },
      { name: "吉水神社", address: "吉野郡吉野町吉野山579", lat: 34.3656, lng: 135.8675, memo: "後醍醐天皇ゆかりの神社。一目千本の絶景ビューポイント。", websiteUrl: "https://www.yoshimizu-shrine.com/", wikiTitle: "吉水神社" },
      { name: "如意輪寺", address: "吉野郡吉野町吉野山1024", lat: 34.3572, lng: 135.8631, memo: "南朝ゆかりの古刹。楠木正行の辞世の句でも知られる。", websiteUrl: "https://ja.kyoto.travel/", wikiTitle: "如意輪寺" },
      { name: "吉野水分神社", address: "吉野郡吉野町吉野山1612", lat: 34.3403, lng: 135.8636, memo: "子授けの神様として信仰される、桃山様式の美しい社殿。", websiteUrl: "https://ja.kyoto.travel/", wikiTitle: "吉野水分神社" },
      { name: "金峯神社", address: "吉野郡吉野町吉野山1651", lat: 34.3272, lng: 135.8544, memo: "吉野山の最奥・奥千本に佇む、静寂に包まれた神社。", websiteUrl: "https://ja.kyoto.travel/", wikiTitle: "金峯神社" },
      { name: "吉野ロープウェイ", address: "吉野郡吉野町吉野山679", lat: 34.3689, lng: 135.8636, memo: "日本最古級のロープウェイ。山麓と山上を結ぶ。", websiteUrl: "https://ja.kyoto.travel/", wikiTitle: "吉野ロープウェイ" },
      { name: "吉野山歴史資料館", address: "吉野郡吉野町吉野山1612", lat: 34.3411, lng: 135.8636, memo: "吉野の歴史と文化を紹介する資料館。", websiteUrl: "https://ja.kyoto.travel/", wikiTitle: "吉野町" },
      { name: "高城山展望台", address: "吉野郡吉野町吉野山", lat: 34.3466, lng: 135.8622, memo: "吉野山を一望できる、隠れた絶景スポット。", websiteUrl: "https://ja.kyoto.travel/", wikiTitle: "吉野山" },
      { name: "桜本坊", address: "吉野郡吉野町吉野山98", lat: 34.3651, lng: 135.8664, memo: "天武天皇ゆかりと伝わる、金峯山寺の格式高い塔頭寺院。", websiteUrl: "https://ja.kyoto.travel/", wikiTitle: "桜本坊" },
      { name: "竹林院群芳園", address: "吉野郡吉野町吉野山2378", lat: 34.358, lng: 135.8654, memo: "大和三庭園の一つに数えられる、池泉回遊式の名庭園。", websiteUrl: "https://chikurin.co.jp/", wikiTitle: "竹林院_(吉野町)" },
    ],
  },
  {
    key: "asuka",
    areaId: "4f3f815e-c209-4123-8930-1153c4fca4d9",
    prefectureId: "dcfe71f9-c52c-44fc-b29f-9e4ccaccca73",
    areaName: "飛鳥",
    prefectureName: "奈良県",
    tagNames: ["定番観光", "学生旅行"],
    purposeNames: ["城・史跡", "お寺", "自然"],
    titles: {
      0: "石舞台と高松塚古墳、古代日本のロマンを巡る日帰りプラン",
      1: "甘樫丘の絶景と古代遺跡、飛鳥の歴史を歩く旅",
      2: "石舞台・飛鳥寺・橘寺、古代飛鳥をゆったり巡る旅",
      3: "日本のはじまりの地・飛鳥を味わい尽くす、じっくり旅",
      4: "古代ロマンあふれる飛鳥をとことん探訪する旅",
    },
    spots: [
      { name: "高松塚古墳", address: "高市郡明日香村平田", lat: 34.4622, lng: 135.8189, memo: "極彩色の壁画が発見されたことで一躍有名になった古墳。", websiteUrl: "https://www.asukabito.or.jp/", wikiTitle: "高松塚古墳" },
      { name: "石舞台古墳", address: "高市郡明日香村島庄254", lat: 34.4661, lng: 135.8228, memo: "巨石を組み上げた、日本最大級の石室を持つ古墳。", websiteUrl: "https://www.asukabito.or.jp/", wikiTitle: "石舞台古墳" },
      { name: "飛鳥寺", address: "高市郡明日香村飛鳥682", lat: 34.4744, lng: 135.8228, memo: "日本最古の本格的寺院。飛鳥大仏が今も本尊として佇む。", websiteUrl: "https://ja.kyoto.travel/", wikiTitle: "飛鳥寺" },
      { name: "甘樫丘", address: "高市郡明日香村豊浦", lat: 34.4761, lng: 135.8161, memo: "飛鳥の里を一望できる丘。大和三山も見渡せる。", websiteUrl: "https://www.asukabito.or.jp/", wikiTitle: "甘樫丘" },
      { name: "橘寺", address: "高市郡明日香村橘532", lat: 34.4667, lng: 135.8233, memo: "聖徳太子生誕の地とされる古刹。", websiteUrl: "https://ja.kyoto.travel/", wikiTitle: "橘寺" },
      { name: "酒船石遺跡", address: "高市郡明日香村岡", lat: 34.4711, lng: 135.8214, memo: "用途不明の謎めいた石造物が残る、古代の遺構。", websiteUrl: "https://www.asukabito.or.jp/", wikiTitle: "酒船石" },
      { name: "奈良文化財研究所飛鳥資料館", address: "高市郡明日香村奥山601", lat: 34.4783, lng: 135.8156, memo: "飛鳥時代の出土品や資料を展示する専門博物館。", websiteUrl: "https://www.nabunken.go.jp/asuka/", wikiTitle: "飛鳥資料館" },
      { name: "岡寺", address: "高市郡明日香村岡806", lat: 34.4694, lng: 135.8242, memo: "日本最初の厄除け霊場として信仰を集める古刹。", websiteUrl: "https://www.okadera3307.com/", wikiTitle: "岡寺" },
      { name: "天武・持統天皇陵", address: "高市郡明日香村野口", lat: 34.4708, lng: 135.8175, memo: "夫婦で合葬された、日本初の八角形の天皇陵。", websiteUrl: "https://ja.kyoto.travel/", wikiTitle: "天武・持統天皇陵" },
      { name: "亀石", address: "高市郡明日香村川原", lat: 34.47, lng: 135.8189, memo: "亀の形をした、飛鳥の数ある謎の石造物の一つ。", websiteUrl: "https://www.asukabito.or.jp/", wikiTitle: "亀石_(明日香村)" },
      { name: "飛鳥京跡", address: "高市郡明日香村岡", lat: 34.4728, lng: 135.8217, memo: "飛鳥時代の宮殿跡と伝わる、発掘調査が進む史跡。", websiteUrl: "https://www.asukabito.or.jp/", wikiTitle: "飛鳥京跡" },
    ],
  },
  // ---- 東京都 ----
  {
    key: "asakusa_ueno",
    areaId: "8b87b993-6866-4a46-beaf-02695124635f",
    prefectureId: "07c1d2fc-83b2-48aa-9cfc-3bca703bd9ef",
    areaName: "浅草・上野",
    prefectureName: "東京都",
    tagNames: ["定番観光", "グルメ"],
    purposeNames: ["お寺", "動物園・水族館", "美術館・博物館"],
    titles: {
      0: "雷門とスカイツリー、下町情緒あふれる浅草さんぽプラン",
      1: "浅草寺の参道とパンダに会える、上野・浅草満喫旅",
      2: "仲見世通りから博物館まで、浅草・上野をゆったり巡る旅",
      3: "下町グルメと文化施設めぐり。浅草・上野を味わい尽くす旅",
      4: "浅草・上野の魅力をとことん楽しむ、じっくり滞在の旅",
    },
    spots: [
      { name: "浅草寺", address: "台東区浅草2丁目3-1", lat: 35.7148, lng: 139.7967, memo: "東京最古の寺院。雷門と仲見世通りで知られる浅草の中心。", websiteUrl: "https://www.senso-ji.jp/", wikiTitle: "浅草寺" },
      { name: "雷門", address: "台東区浅草1丁目2", lat: 35.7107, lng: 139.7965, memo: "大きな赤提灯が目印の、浅草寺の総門。", websiteUrl: "https://www.senso-ji.jp/", wikiTitle: "雷門" },
      { name: "仲見世通り", address: "台東区浅草1〜2丁目", lat: 35.7127, lng: 139.7965, memo: "雷門から浅草寺まで続く、日本最古の商店街の一つ。", websiteUrl: "https://www.asakusa-nakamise.jp/", wikiTitle: "仲見世通り" },
      { name: "東京スカイツリー", address: "墨田区押上1丁目1-2", lat: 35.7101, lng: 139.8107, memo: "高さ634m、世界有数の高さを誇る東京の新名所。", websiteUrl: "https://www.tokyo-skytree.jp/", wikiTitle: "東京スカイツリー" },
      { name: "上野恩賜公園", address: "台東区上野公園5-20", lat: 35.7147, lng: 139.7737, memo: "博物館や動物園が集まる、東京を代表する文化公園。", websiteUrl: "https://www.kensetsu.metro.tokyo.lg.jp/jimusho/toubuk/ueno/", wikiTitle: "上野恩賜公園" },
      { name: "上野動物園", address: "台東区上野公園9-83", lat: 35.7161, lng: 139.7712, memo: "パンダで有名な、日本最古の動物園。", websiteUrl: "https://www.tokyo-zoo.net/zoo/ueno/", wikiTitle: "上野動物園" },
      { name: "東京国立博物館", address: "台東区上野公園13-9", lat: 35.7188, lng: 139.7765, memo: "日本最大級の博物館。国宝・重要文化財を多数収蔵。", websiteUrl: "https://www.tnm.jp/", wikiTitle: "東京国立博物館" },
      { name: "アメ横", address: "台東区上野4〜6丁目", lat: 35.7096, lng: 139.7745, memo: "活気あふれる、上野を代表する商店街・市場。", websiteUrl: "https://www.ameyoko.net/", wikiTitle: "アメ横" },
      { name: "浅草花やしき", address: "台東区浅草2丁目28-1", lat: 35.7159, lng: 139.7942, memo: "日本最古の遊園地。レトロな雰囲気が魅力。", websiteUrl: "https://www.hanayashiki.net/", wikiTitle: "浅草花やしき" },
      { name: "隅田公園", address: "台東区花川戸1丁目", lat: 35.7133, lng: 139.8006, memo: "隅田川沿いに広がる桜の名所。スカイツリーの眺めも良い。", websiteUrl: "https://ja.kyoto.travel/", wikiTitle: "隅田公園" },
      { name: "隅田川", address: "台東区花川戸", lat: 35.7115, lng: 139.8011, memo: "水上バスで浅草からお台場方面へも行ける、東京の代表的な川。", websiteUrl: "https://www.suijobus.co.jp/", wikiTitle: "隅田川" },
      { name: "不忍池", address: "台東区上野公園", lat: 35.7137, lng: 139.7712, memo: "夏には一面に蓮の花が咲く、上野公園内の池。", websiteUrl: "https://ja.kyoto.travel/", wikiTitle: "不忍池" },
      { name: "谷中銀座商店街", address: "台東区谷中3丁目", lat: 35.7255, lng: 139.7669, memo: "昔ながらの下町情緒が残る、猫の街としても有名な商店街。", websiteUrl: "https://www.yanakaginza.com/", wikiTitle: "谷中銀座商店街" },
      { name: "上野東照宮", address: "台東区上野公園9-88", lat: 35.7169, lng: 139.7726, memo: "金色殿で知られる、徳川家康を祀る絢爛豪華な神社。", websiteUrl: "https://www.uenotoshogu.com/", wikiTitle: "上野東照宮" },
    ],
  },
  {
    key: "shibuya_harajuku",
    areaId: "44decacd-6bed-4dfe-83a5-56944758a5d3",
    prefectureId: "07c1d2fc-83b2-48aa-9cfc-3bca703bd9ef",
    areaName: "渋谷・原宿",
    prefectureName: "東京都",
    tagNames: ["定番観光", "学生旅行"],
    purposeNames: ["ショッピング", "神社", "自然"],
    titles: {
      0: "スクランブル交差点と竹下通り、若者の街を巡る日帰りプラン",
      1: "渋谷の絶景展望台と明治神宮の杜、対照的な魅力を巡る旅",
      2: "ハチ公前から表参道まで、渋谷・原宿をゆったり満喫する旅",
      3: "最新スポットと歴史ある杜。渋谷・原宿を味わい尽くす旅",
      4: "渋谷・原宿のトレンドと自然をとことん楽しむ旅",
    },
    spots: [
      { name: "渋谷スクランブル交差点", address: "渋谷区道玄坂2丁目", lat: 35.6595, lng: 139.7005, memo: "一度に数千人が行き交う、世界的に有名な交差点。", websiteUrl: "https://ja.kyoto.travel/", wikiTitle: "渋谷スクランブル交差点" },
      { name: "渋谷スクランブルスクエア", address: "渋谷区渋谷2丁目24-12", lat: 35.658, lng: 139.7016, memo: "展望施設「渋谷スカイ」から東京の街を一望できる複合施設。", websiteUrl: "https://www.shibuya-scramble-square.com/", wikiTitle: "渋谷スクランブルスクエア" },
      { name: "明治神宮", address: "渋谷区代々木神園町1-1", lat: 35.6764, lng: 139.6993, memo: "都心とは思えない広大な杜に鎮座する、明治天皇を祀る神社。", websiteUrl: "https://www.meijijingu.or.jp/", wikiTitle: "明治神宮" },
      { name: "竹下通り", address: "渋谷区神宮前1丁目", lat: 35.6712, lng: 139.7058, memo: "原宿の若者文化を象徴する、ポップな店が並ぶ通り。", websiteUrl: "https://www.takeshita-street.com/", wikiTitle: "竹下通り" },
      { name: "表参道", address: "渋谷区神宮前", lat: 35.6685, lng: 139.71, memo: "けやき並木が美しい、ハイブランドが立ち並ぶ通り。", websiteUrl: "https://ja.kyoto.travel/", wikiTitle: "表参道" },
      { name: "キャットストリート", address: "渋谷区神宮前", lat: 35.6683, lng: 139.705, memo: "セレクトショップが並ぶ、原宿と渋谷をつなぐ裏通り。", websiteUrl: "https://ja.kyoto.travel/", wikiTitle: "キャットストリート" },
      { name: "代々木公園", address: "渋谷区代々木神園町2-1", lat: 35.6717, lng: 139.695, memo: "広大な芝生が広がる、都民の憩いの場。", websiteUrl: "https://www.tokyo-park.or.jp/park/yoyogi/", wikiTitle: "代々木公園" },
      { name: "忠犬ハチ公像", address: "渋谷区道玄坂2丁目", lat: 35.659, lng: 139.7005, memo: "待ち合わせ場所として親しまれる、渋谷のシンボル。", websiteUrl: "https://ja.kyoto.travel/", wikiTitle: "忠犬ハチ公" },
      { name: "渋谷センター街", address: "渋谷区宇田川町", lat: 35.6606, lng: 139.6989, memo: "ショップや飲食店が密集する、渋谷の若者文化の中心地。", websiteUrl: "https://ja.kyoto.travel/", wikiTitle: "渋谷センター街" },
      { name: "明治神宮外苑（いちょう並木）", address: "新宿区霞ヶ丘町", lat: 35.6764, lng: 139.7178, memo: "秋には黄金色に染まる、都内屈指のいちょう並木。", websiteUrl: "https://www.meijijingugaien.jp/", wikiTitle: "明治神宮外苑" },
      { name: "渋谷ヒカリエ", address: "渋谷区渋谷2丁目21-1", lat: 35.659, lng: 139.7028, memo: "アートやカルチャー発信拠点も併設する複合商業施設。", websiteUrl: "https://www.hikarie.jp/", wikiTitle: "渋谷ヒカリエ" },
      { name: "根津美術館", address: "港区南青山6丁目5-1", lat: 35.6636, lng: 139.7178, memo: "表参道近くにある、日本・東洋の古美術品を展示する美術館。", websiteUrl: "https://www.nezu-muse.or.jp/", wikiTitle: "根津美術館" },
    ],
  },
  {
    key: "odaiba",
    areaId: "25725572-d6f1-423f-b9c7-78553ae4af3a",
    prefectureId: "07c1d2fc-83b2-48aa-9cfc-3bca703bd9ef",
    areaName: "お台場・臨海副都心",
    prefectureName: "東京都",
    tagNames: ["家族旅行", "絶景"],
    purposeNames: ["テーマパーク", "夜景", "美術館・博物館"],
    titles: {
      0: "レインボーブリッジとガンダム像、お台場満喫日帰りプラン",
      1: "海辺の絶景とデジタルアート、お台場を楽しむ旅",
      2: "科学館からチームラボまで、お台場をゆったり満喫する旅",
      3: "ベイエリアの魅力をとことん楽しむ、お台場じっくり旅",
      4: "お台場・臨海副都心の見どころをすべて味わう旅",
    },
    spots: [
      { name: "お台場海浜公園", address: "港区台場1丁目4", lat: 35.6297, lng: 139.7739, memo: "人工の砂浜からレインボーブリッジを望む、お台場のシンボル的公園。", websiteUrl: "https://www.tokyo-park.or.jp/park/kaihin/", wikiTitle: "お台場海浜公園" },
      { name: "レインボーブリッジ", address: "港区海岸3丁目〜台場1丁目", lat: 35.6367, lng: 139.7631, memo: "東京湾に架かる、お台場と都心を結ぶ美しい吊り橋。", websiteUrl: "https://www.shutoko.jp/", wikiTitle: "レインボーブリッジ" },
      { name: "フジテレビ本社ビル", address: "港区台場2丁目4-8", lat: 35.6255, lng: 139.7756, memo: "球体展望室が特徴的な、丹下健三設計のテレビ局ビル。", websiteUrl: "https://www.fujitv.co.jp/gotofujitv/", wikiTitle: "フジテレビジョン" },
      { name: "ダイバーシティ東京プラザ", address: "江東区青海1丁目1-10", lat: 35.6253, lng: 139.7752, memo: "実物大ユニコーンガンダム立像がそびえる、複合商業施設。", websiteUrl: "https://mitsui-shopping-park.com/divercity-tokyo/", wikiTitle: "ダイバーシティ東京プラザ" },
      { name: "チームラボプラネッツ", address: "江東区豊洲6丁目1-16", lat: 35.6497, lng: 139.7936, memo: "水に足を浸して鑑賞する、体感型デジタルアートミュージアム。", websiteUrl: "https://www.teamlab.art/jp/e/planets/", wikiTitle: "チームラボプラネッツ" },
      { name: "日本科学未来館", address: "江東区青海2丁目3-6", lat: 35.6197, lng: 139.7761, memo: "最先端の科学技術を体感できる、宇宙飛行士も館長を務めた科学館。", websiteUrl: "https://www.miraikan.jst.go.jp/", wikiTitle: "日本科学未来館" },
      { name: "東京ビッグサイト", address: "江東区有明3丁目11-1", lat: 35.63, lng: 139.793, memo: "逆さピラミッドの外観が印象的な、国内最大級の展示場。", websiteUrl: "https://www.bigsight.jp/", wikiTitle: "東京ビッグサイト" },
      { name: "アクアシティお台場", address: "港区台場1丁目7-1", lat: 35.628, lng: 139.7739, memo: "レインボーブリッジを間近に望む、ショッピング&グルメ施設。", websiteUrl: "https://www.aquacity.jp/", wikiTitle: "アクアシティお台場" },
      { name: "台場公園（台場砲台跡）", address: "港区台場1丁目", lat: 35.6272, lng: 139.7692, memo: "幕末に築かれた砲台跡。お台場の地名の由来となった史跡。", websiteUrl: "https://ja.kyoto.travel/", wikiTitle: "台場_(東京都港区)" },
      { name: "潮風公園", address: "品川区東八潮1-1", lat: 35.6244, lng: 139.7692, memo: "海沿いに広がる、スポーツやピクニックが楽しめる公園。", websiteUrl: "https://www.tokyo-park.or.jp/park/shiokaze/", wikiTitle: "潮風公園" },
      { name: "豊洲市場", address: "江東区豊洲6丁目6-1", lat: 35.6455, lng: 139.7847, memo: "新鮮な魚介と競りの見学が楽しめる、東京の台所。", websiteUrl: "https://www.shijou.metro.tokyo.lg.jp/toyosu/", wikiTitle: "豊洲市場" },
    ],
  },
  {
    key: "kichijoji_mitaka",
    areaId: "03cd9295-1920-468c-85e3-0df11757680e",
    prefectureId: "07c1d2fc-83b2-48aa-9cfc-3bca703bd9ef",
    areaName: "吉祥寺・三鷹",
    prefectureName: "東京都",
    tagNames: ["家族旅行", "学生旅行"],
    purposeNames: ["自然", "美術館・博物館", "ショッピング"],
    titles: {
      0: "井の頭公園とジブリ美術館、吉祥寺さんぽ日帰りプラン",
      1: "自然と文学、吉祥寺・三鷹をのんびり楽しむ旅",
      2: "ハモニカ横丁から太宰治ゆかりの地まで、じっくり巡る旅",
      3: "杉並・武蔵野の緑と文化を味わい尽くす、吉祥寺・三鷹の旅",
      4: "吉祥寺・三鷹の魅力をとことん楽しむ、じっくり滞在の旅",
    },
    spots: [
      { name: "井の頭恩賜公園", address: "武蔵野市御殿山1丁目18-31", lat: 35.701, lng: 139.5744, memo: "ボート池を中心とした、都内屈指の桜の名所。", websiteUrl: "https://www.kensetsu.metro.tokyo.lg.jp/jimusho/seibuk/inokashira/", wikiTitle: "井の頭恩賜公園" },
      { name: "三鷹の森ジブリ美術館", address: "三鷹市下連雀1丁目1-83", lat: 35.696, lng: 139.5703, memo: "スタジオジブリ作品の世界観を体感できる、人気の美術館。", websiteUrl: "https://www.ghibli-museum.jp/", wikiTitle: "三鷹の森ジブリ美術館" },
      { name: "吉祥寺サンロード商店街", address: "武蔵野市吉祥寺本町1丁目", lat: 35.7031, lng: 139.5794, memo: "吉祥寺駅前から続く、アーケード付きの商店街。", websiteUrl: "https://www.sun-road.or.jp/", wikiTitle: "吉祥寺サンロード商店街" },
      { name: "ハモニカ横丁", address: "武蔵野市吉祥寺本町1丁目1", lat: 35.7036, lng: 139.5786, memo: "戦後の闇市の名残を残す、狭い路地に飲食店が並ぶ一角。", websiteUrl: "https://ja.kyoto.travel/", wikiTitle: "ハモニカ横丁" },
      { name: "井の頭自然文化園", address: "武蔵野市御殿山1丁目17-6", lat: 35.7025, lng: 139.5772, memo: "ゾウのはな子で親しまれた、動物園と水生物館からなる施設。", websiteUrl: "https://www.tokyo-zoo.net/zoo/ino/", wikiTitle: "井の頭自然文化園" },
      { name: "武蔵野八幡宮", address: "武蔵野市吉祥寺本町1丁目1-25", lat: 35.7039, lng: 139.5793, memo: "吉祥寺の総鎮守として親しまれる、静かな杜の神社。", websiteUrl: "https://ja.kyoto.travel/", wikiTitle: "武蔵野八幡宮" },
      { name: "太宰治文学サロン", address: "三鷹市下連雀3丁目16-14", lat: 35.6976, lng: 139.5622, memo: "三鷹に住んだ文豪・太宰治の資料を展示する小さな文学館。", websiteUrl: "https://www.city.mitaka.lg.jp/dazai/", wikiTitle: "太宰治文学サロン" },
      { name: "禅林寺（太宰治の墓）", address: "三鷹市下連雀4丁目18-20", lat: 35.6963, lng: 139.5645, memo: "太宰治と森鴎外の墓があることで知られる寺院。", websiteUrl: "https://ja.kyoto.travel/", wikiTitle: "禅林寺_(三鷹市)" },
      { name: "玉川上水緑道", address: "三鷹市〜武蔵野市", lat: 35.6987, lng: 139.5644, memo: "江戸時代の水路沿いに整備された、緑豊かな散策路。", websiteUrl: "https://ja.kyoto.travel/", wikiTitle: "玉川上水" },
      { name: "山本有三記念館", address: "三鷹市下連雀2丁目12-27", lat: 35.6989, lng: 139.5678, memo: "作家・山本有三が暮らした、洋館を利用した記念館。", websiteUrl: "https://www.city.mitaka.lg.jp/yamamotoyuzo/", wikiTitle: "山本有三記念館" },
    ],
  },
  // ---- 福岡県 ----
  {
    key: "fukuoka_city",
    areaId: "7b539a5c-07ea-40d5-bac7-a9aa600675e4",
    prefectureId: "d744ba03-26b2-4e7f-9b95-89b8ba2d3fac",
    areaName: "福岡市内",
    prefectureName: "福岡県",
    tagNames: ["グルメ", "定番観光"],
    purposeNames: ["神社", "城・史跡", "離島"],
    titles: {
      0: "屋台グルメと福岡タワー、博多の街を楽しむ日帰りプラン",
      1: "櫛田神社と中洲屋台、博多の伝統と活気を巡る旅",
      2: "大濠公園から能古島まで、福岡の自然と街をゆったり巡る旅",
      3: "博多の歴史とグルメを味わい尽くす、福岡じっくり旅",
      4: "福岡の魅力をとことん楽しむ、じっくり滞在の旅",
    },
    spots: [
      { name: "福岡タワー", address: "福岡市早良区百道浜2丁目3-26", lat: 33.5933, lng: 130.3511, memo: "海浜タワーとして日本一の高さを誇る、福岡のランドマーク。", websiteUrl: "https://www.fukuokatower.co.jp/", wikiTitle: "福岡タワー" },
      { name: "大濠公園", address: "福岡市中央区大濠公園1-2", lat: 33.5878, lng: 130.3789, memo: "大きな池を中心に整備された、市民の憩いの都市公園。", websiteUrl: "https://ohorikouen.jp/", wikiTitle: "大濠公園" },
      { name: "中洲屋台街", address: "福岡市博多区中洲", lat: 33.5919, lng: 130.4067, memo: "那珂川沿いに屋台が並ぶ、福岡の夜の名物風景。", websiteUrl: "https://ja.kyoto.travel/", wikiTitle: "中洲" },
      { name: "川端通商店街", address: "福岡市博多区上川端町6-135", lat: 33.5928, lng: 130.4106, memo: "130年以上の歴史を持つ、博多を代表するアーケード商店街。", websiteUrl: "https://www.hakata.or.jp/", wikiTitle: "川端通商店街" },
      { name: "櫛田神社", address: "福岡市博多区上川端町1-41", lat: 33.5928, lng: 130.4114, memo: "博多祇園山笠でも知られる、博多の総鎮守。", websiteUrl: "https://hakatayamakasa.com/", wikiTitle: "櫛田神社_(福岡市)" },
      { name: "福岡城跡（舞鶴公園）", address: "福岡市中央区城内", lat: 33.5883, lng: 130.3806, memo: "黒田長政が築いた城の跡地。桜の名所としても人気。", websiteUrl: "https://saifukuoka.jp/", wikiTitle: "福岡城" },
      { name: "博多駅（JR博多シティ）", address: "福岡市博多区博多駅中央街1-1", lat: 33.5897, lng: 130.4207, memo: "屋上庭園やグルメ街も充実する、博多の玄関口。", websiteUrl: "https://www.jrhakatacity.com/", wikiTitle: "博多駅" },
      { name: "ベイサイドプレイス博多", address: "福岡市博多区築港本町13-6", lat: 33.6014, lng: 130.4103, memo: "能古島行きの船も出る、博多港のウォーターフロント施設。", websiteUrl: "https://www.baysideplace.jp/", wikiTitle: "ベイサイドプレイス博多" },
      { name: "福岡市博物館", address: "福岡市早良区百道浜3丁目1-1", lat: 33.5928, lng: 130.3486, memo: "国宝「金印」を収蔵する、福岡の歴史と文化を伝える博物館。", websiteUrl: "https://museum.city.fukuoka.jp/", wikiTitle: "福岡市博物館" },
      { name: "住吉神社（博多）", address: "福岡市博多区住吉3丁目1-51", lat: 33.5878, lng: 130.4103, memo: "全国の住吉神社の中でも最古とされる、格式高い神社。", websiteUrl: "https://www.sumiyoshijinja.or.jp/", wikiTitle: "住吉神社_(福岡市)" },
      { name: "天神", address: "福岡市中央区天神2丁目", lat: 33.5906, lng: 130.3986, memo: "百貨店や地下街が広がる、福岡随一の繁華街。", websiteUrl: "https://ja.kyoto.travel/", wikiTitle: "天神_(福岡市)" },
      { name: "能古島", address: "福岡市西区能古", lat: 33.6383, lng: 130.3081, memo: "博多湾に浮かぶ、花と自然が楽しめる離島。フェリーで10分。", websiteUrl: "https://nokonoshima.com/", wikiTitle: "能古島" },
    ],
  },
  {
    key: "dazaifu",
    areaId: "e838945d-e393-4cfc-becf-80d86e438818",
    prefectureId: "d744ba03-26b2-4e7f-9b95-89b8ba2d3fac",
    areaName: "太宰府",
    prefectureName: "福岡県",
    tagNames: ["定番観光", "紅葉"],
    purposeNames: ["神社", "お寺", "美術館・博物館"],
    titles: {
      0: "梅ヶ枝餅片手に、学問の神様・太宰府天満宮を巡るプラン",
      1: "天満宮と九州国立博物館、太宰府の歴史と文化を巡る旅",
      2: "竈門神社から政庁跡まで、太宰府をゆったり巡る旅",
      3: "太宰府の歴史と信仰を味わい尽くす、じっくり旅",
      4: "太宰府の隠れた名所までとことん巡る旅",
    },
    spots: [
      { name: "太宰府天満宮", address: "太宰府市宰府4丁目7-1", lat: 33.5219, lng: 130.5347, memo: "学問の神様・菅原道真公を祀る、全国天満宮の総本社。", websiteUrl: "https://www.dazaifutenmangu.or.jp/", wikiTitle: "太宰府天満宮" },
      { name: "太宰府天満宮参道", address: "太宰府市宰府3丁目", lat: 33.5206, lng: 130.5333, memo: "名物・梅ヶ枝餅の店が並ぶ、賑やかな参道商店街。", websiteUrl: "https://www.dazaifutenmangu.or.jp/", wikiTitle: "太宰府天満宮" },
      { name: "九州国立博物館", address: "太宰府市石坂4丁目7-2", lat: 33.5203, lng: 130.5378, memo: "アジア諸国との交流の歴史を紹介する、国内4番目の国立博物館。", websiteUrl: "https://www.kyuhaku.jp/", wikiTitle: "九州国立博物館" },
      { name: "大宰府政庁跡", address: "太宰府市観世音寺4丁目6", lat: 33.5175, lng: 130.5203, memo: "かつて「遠の朝廷」と呼ばれた、古代九州の行政中心地の跡。", websiteUrl: "https://ja.kyoto.travel/", wikiTitle: "大宰府" },
      { name: "観世音寺", address: "太宰府市観世音寺5丁目6-1", lat: 33.5192, lng: 130.5219, memo: "日本最古級の梵鐘を持つ、奈良時代創建の古刹。", websiteUrl: "https://ja.kyoto.travel/", wikiTitle: "観世音寺" },
      { name: "光明禅寺", address: "太宰府市宰府2丁目16-1", lat: 33.5222, lng: 130.5314, memo: "「苔寺」とも呼ばれる、枯山水庭園が美しい禅寺。", websiteUrl: "https://ja.kyoto.travel/", wikiTitle: "光明禅寺" },
      { name: "竈門神社", address: "太宰府市内山883", lat: 33.5364, lng: 130.5439, memo: "宝満山の麓に鎮座する、縁結びで人気の神社。", websiteUrl: "https://kamadojinja.or.jp/", wikiTitle: "竈門神社" },
      { name: "戒壇院", address: "太宰府市観世音寺5丁目7-10", lat: 33.5183, lng: 130.5211, memo: "日本三戒壇の一つに数えられる、僧の受戒を行った寺院。", websiteUrl: "https://ja.kyoto.travel/", wikiTitle: "戒壇院_(太宰府市)" },
      { name: "坂本八幡宮", address: "太宰府市坂本3丁目14-23", lat: 33.5292, lng: 130.5142, memo: "元号「令和」の典拠となった万葉集の梅花の宴の舞台。", websiteUrl: "https://ja.kyoto.travel/", wikiTitle: "坂本八幡宮" },
      { name: "天開稲荷社", address: "太宰府市宰府4丁目7-1", lat: 33.5236, lng: 130.5358, memo: "太宰府天満宮奥の山中に鎮座する、隠れたパワースポット。", websiteUrl: "https://www.dazaifutenmangu.or.jp/", wikiTitle: "太宰府天満宮" },
    ],
  },
  {
    key: "mojiko",
    areaId: "0d24fc86-569f-4d02-9abb-878fe191a0c3",
    prefectureId: "d744ba03-26b2-4e7f-9b95-89b8ba2d3fac",
    areaName: "門司港",
    prefectureName: "福岡県",
    tagNames: ["絶景", "グルメ"],
    purposeNames: ["夜景", "鉄道旅", "美術館・博物館"],
    titles: {
      0: "レトロな洋館が並ぶ、門司港ノスタルジックさんぽプラン",
      1: "関門海峡の絶景とレトロ建築、門司港を満喫する旅",
      2: "はね橋と海峡ミュージアム、門司港をゆったり巡る旅",
      3: "大正ロマンあふれる門司港を味わい尽くす、じっくり旅",
      4: "関門海峡と門司港の魅力をとことん楽しむ旅",
    },
    spots: [
      { name: "門司港レトロ地区", address: "北九州市門司区港町", lat: 33.9481, lng: 130.9639, memo: "大正時代の洋館が立ち並ぶ、ノスタルジックな港町エリア。", websiteUrl: "https://www.mojiko.info/", wikiTitle: "門司港レトロ" },
      { name: "旧門司三井倶楽部", address: "北九州市門司区港町7-1", lat: 33.9483, lng: 130.9633, memo: "アインシュタインも宿泊した、大正期の社交倶楽部建築。", websiteUrl: "https://www.mojiko.info/", wikiTitle: "旧門司三井倶楽部" },
      { name: "旧大阪商船", address: "北九州市門司区港町7-18", lat: 33.9486, lng: 130.9631, memo: "オレンジ色のドームが目印の、大正期の商船会社社屋。", websiteUrl: "https://www.mojiko.info/", wikiTitle: "門司港レトロ" },
      { name: "関門海峡ミュージアム", address: "北九州市門司区西海岸1丁目3-3", lat: 33.95, lng: 130.9631, memo: "海峡の歴史と自然を体感できる、体験型ミュージアム。", websiteUrl: "https://www.mojiko.info/kaikyo/", wikiTitle: "関門海峡ミュージアム" },
      { name: "門司港駅", address: "北九州市門司区西海岸1丁目5-31", lat: 33.9469, lng: 130.9622, memo: "国の重要文化財に指定された、ネオ・ルネサンス様式の木造駅舎。", websiteUrl: "https://www.jrkyushu.co.jp/", wikiTitle: "門司港駅" },
      { name: "関門橋", address: "北九州市門司区旧門司港周辺", lat: 33.9556, lng: 130.9564, memo: "本州と九州を結ぶ、関門海峡に架かる巨大な吊り橋。", websiteUrl: "https://ja.kyoto.travel/", wikiTitle: "関門橋" },
      { name: "和布刈公園", address: "北九州市門司区門司3492", lat: 33.9597, lng: 130.9553, memo: "関門海峡と関門橋を間近に望む、絶景の展望公園。", websiteUrl: "https://ja.kyoto.travel/", wikiTitle: "和布刈公園" },
      { name: "ブルーウィングもじ", address: "北九州市門司区港町4", lat: 33.9489, lng: 130.9636, memo: "日本最大級の歩行者専用はね橋。1日数回跳ね上がる。", websiteUrl: "https://www.mojiko.info/", wikiTitle: "ブルーウィングもじ" },
      { name: "出光美術館（門司）", address: "北九州市門司区東港町2-3", lat: 33.9481, lng: 130.9678, memo: "出光興産創業者のコレクションを展示する美術館。", websiteUrl: "https://idemitsu-museum.or.jp/moji/", wikiTitle: "出光美術館_(門司)" },
      { name: "関門海峡（人道入口）", address: "北九州市門司区みもすそ川町", lat: 33.9569, lng: 130.9558, memo: "海底トンネルを徒歩で渡れる、全国でも珍しい関門トンネル人道。", websiteUrl: "https://ja.kyoto.travel/", wikiTitle: "関門海峡" },
    ],
  },
];

async function main() {
  const imageCache = new Map<string, string | null>(Object.entries(existingPhotoCache as Record<string, string>));
  await generateAreas(AREAS, imageCache, "batch2");
  console.log("\n完了しました。");
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
